name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true
      platforms:
        description: image platforms
        required: true
        default: linux/amd64, linux/arm64

env:
  CI: true

jobs:
  publish:
    name: docker-publish
    runs-on: dev-server
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          push: true
          target: proxy
          tags: subsquid/yellowstone-geyser-proxy:${{ inputs.tag }}